spring:
  application:
    name: movies-service
  profiles:
    active: local
server:
  port: 8082

restClient:
  moviesInfoUrl: http://localhost:8080/v1/movieinfos
  reviewsUrl: http://localhost:8081/v1/reviews
---


spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

---

logging:
  level:
    org.springframework.web: DEBUG
